"""Export benchmark results to JSON and Markdown."""

from __future__ import annotations

import json
from pathlib import Path

from inferbox.models import BenchmarkResult


def export_json(result: BenchmarkResult, output_path: str) -> None:
    """Export results to JSON file."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(result.to_json())


def export_markdown(result: BenchmarkResult, output_path: str) -> None:
    """Export results to Markdown file."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        f"# InferBox Results — {result.model_name}",
        "",
        f"**Date:** {result.timestamp}",
        f"**InferBox Version:** {result.inferbox_version}",
        f"**Backend:** {result.backend}",
        "",
        "## Hardware",
        "",
        f"| Property | Value |",
        f"|:---|:---|",
        f"| CPU | {result.hardware.cpu_name} |",
        f"| Architecture | {result.hardware.cpu_arch} |",
        f"| Cores | {result.hardware.cpu_cores_physical}P / {result.hardware.cpu_cores_logical}L |",
        f"| RAM | {result.hardware.ram_total_gb:.1f} GB |",
        f"| OS | {result.hardware.os_name} {result.hardware.os_version} |",
    ]

    if result.hardware.gpu_name:
        lines.append(f"| GPU | {result.hardware.gpu_name} |")
    if result.hardware.npu_name:
        lines.append(f"| NPU | {result.hardware.npu_name} |")
    if result.hardware.memory_bandwidth_gb_s:
        lines.append(f"| Est. Bandwidth | ~{result.hardware.memory_bandwidth_gb_s:.0f} GB/s |")

    lines.extend(["", "## Results", "", "| Metric | Value |", "|:---|:---|"])

    if result.speed:
        s = result.speed
        lines.append(f"| Tok/s (generation) | {s.tok_s_generation:.1f} |")
        if s.tok_s_prompt > 0:
            lines.append(f"| Tok/s (prompt) | {s.tok_s_prompt:.1f} |")
        lines.append(f"| TTFT | {s.ttft_seconds:.2f}s |")
        if s.sustained_tok_s is not None:
            lines.append(f"| Sustained Tok/s | {s.sustained_tok_s:.1f} |")
        if s.throttle_percent is not None:
            lines.append(f"| Throttle | {s.throttle_percent:+.1f}% |")

    if result.memory:
        m = result.memory
        lines.append(f"| Peak RAM | {m.peak_ram_mb / 1024:.1f} GB |")
        lines.append(f"| Model RAM | {m.model_ram_mb / 1024:.1f} GB |")
        lines.append(f"| RAM Usage | {m.ram_utilization_pct:.0f}% |")

    if result.power:
        p = result.power
        lines.append(f"| Power | {p.avg_power_watts:.1f} W ({p.method}) |")
        lines.append(f"| Tok/s/W | {p.tok_s_per_watt:.2f} |")
        lines.append(f"| Energy/token | {p.energy_per_token_mj:.1f} mJ |")

    if result.quality:
        q = result.quality
        if q.mmlu_accuracy is not None:
            lines.append(f"| mini-MMLU | {q.mmlu_accuracy:.1f}% |")
        if q.humaneval_pass_rate is not None:
            lines.append(f"| mini-HumanEval | {q.humaneval_pass_rate:.1f}% |")

    if result.edge_score is not None:
        lines.extend([
            "",
            f"## Edge Score: {result.edge_score}/100",
        ])

    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by InferBox v{result.inferbox_version}*")
    lines.append("")

    path.write_text("\n".join(lines))
