"""Export BenchWolf results to JSON or Markdown."""

from pathlib import Path

from benchwolf.models import BenchmarkResult


def export_json(result: BenchmarkResult, output_path: str) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(result.to_json(), encoding="utf-8")


def export_markdown(result: BenchmarkResult, output_path: str) -> None:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# BenchWolf Results — {result.model_name}",
        "",
        f"- Date: {result.timestamp}",
        f"- BenchWolf: {result.benchwolf_version}",
        f"- Backend: {result.backend}",
        f"- Hardware: {result.hardware.summary}",
        "",
        "## Results",
        "",
        "| Metric | Value | Provenance |",
        "|---|---:|---|",
    ]
    if result.speed:
        lines.extend(
            [
                f"| Generation | {result.speed.tok_s_generation:.1f} tok/s | measured |",
                f"| TTFT | {result.speed.ttft_seconds:.2f} s | measured |",
            ]
        )
    if result.memory:
        lines.extend(
            [
                f"| Peak system RAM | {result.memory.peak_system_ram_mb / 1024:.1f} GB | sampled |",
                f"| Inference RAM delta | {result.memory.inference_delta_mb:.1f} MB | system-wide |",
            ]
        )
    if result.power:
        power = result.power
        watts = "—" if power.avg_power_watts is None else f"{power.avg_power_watts:.2f} W"
        lines.append(f"| Power | {watts} | {power.source}: {power.method} |")
    if result.quality and result.quality.mmlu_accuracy is not None:
        lines.append(f"| mini-MMLU | {result.quality.mmlu_accuracy:.1f}% | measured |")
    if result.edge_score is not None:
        kind = "partial" if result.edge_score_is_partial else "full"
        lines.extend(["", f"## Edge Score v{result.edge_score_version}: {result.edge_score}/100 ({kind})"])
    lines.extend(["", "Generated by BenchWolf.", ""])
    path.write_text("\n".join(lines), encoding="utf-8")
